<?php

return [
    [
        'name' => 'wxappid',
        'title' => '微信小程序AppID',
        'type' => 'string',
        'content' => [],
        'value' => 'wxa43c39d675290e5e',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxappsecret',
        'title' => '微信小程序AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => 'ef4e78466fc6c1f6bcd7515f3c912c5a',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'couponsn',
        'title' => '微信支付商户号ID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'paykey',
        'title' => '微信支付商户的密钥',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cert',
        'title' => '微信支付API证书cert',
        'type' => 'file',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'key',
        'title' => '微信支付API证书key',
        'type' => 'file',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
